# Basic
title: Ruan Weizhang
subtitle: Welcome to my blog
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
#description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="http://ruanweizhang.cn">@eric</a>

url: http://ruanweizhang.cn

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: ruanweizhang
    # duoshuo: 
    
# Social
social:
    facebook: ruanweizhang
    github: ruanweizhang
    mail: ruanweizhang@gmail.com

# Google Analytics
ga:
    id: UA-55434310-1
    host: ruanweizhang.cn
